from re import Pattern

import re2

from risk_assessment.classification.identifiers import Identifier

SEPARATOR: str = r"(?:,?\s*)?"

DIRECTIONAL: str = (
    r"(?:"
    r"(?:(?:n|s|e|w|ne|nw|se|sw)\.?)"
    r"|"
    r"(?:north|south|east|west|north[- ]?east|north[- ]?west|south[- ]?east|south[- ]west)"
    r")"
)
SUFFIX: str = (
    r"(?:(?:"
    r"ALLEE|ALLEY|ALLY|ALY|"
    r"ANEX|ANNEX|ANNX|ANX|"
    r"ARC|ARCADE|"
    r"AV|AVE|AVEN|AVENU|AVENUE|AVN|AVNUE|"
    r"BAYOO|BAYOU|"
    r"BCH|BEACH|"
    r"BEND|BND|"
    r"BG|"
    r"BGS|"
    r"BLF|BLUF|BLUFF|"
    r"BLFS|BLUFFS|"
    r"BLVD|BOUL|BOULEVARD|BOULV|"
    r"BOT|BOTTM|BOTTOM|"
    r"BR|"
    r"BRANCH|"
    r"BRDGE|"
    r"BRG|"
    r"BRIDGE|"
    r"BRK|"
    r"BRKS|"
    r"BRNCH|"
    r"BROOK|"
    r"BROOKS|"
    r"BTM|"
    r"BURG|"
    r"BURGS|"
    r"BYP|"
    r"BYPA|"
    r"BYPAS|"
    r"BYPASS|"
    r"BYPS|"
    r"BYU|"
    r"CAMP|"
    r"CANYN|"
    r"CANYON|"
    r"CAPE|"
    r"CAUSEWAY|"
    r"CAUSWA|"
    r"CEN|"
    r"CENT|"
    r"CENTER|"
    r"CENTERS|"
    r"CENTR|"
    r"CENTRE|"
    r"CIR|"
    r"CIRC|"
    r"CIRCL|"
    r"CIRCLE|"
    r"CIRCLES|"
    r"CIRS|"
    r"CLB|"
    r"CLF|"
    r"CLFS|"
    r"CLIFF|"
    r"CLIFFS|"
    r"CLUB|"
    r"CMN|"
    r"CMNS|"
    r"CMP|"
    r"CNTER|"
    r"CNTR|"
    r"CNYN|"
    r"COMMON|"
    r"COMMONS|"
    r"COR|"
    r"CORNER|"
    r"CORNERS|"
    r"CORS|"
    r"COURSE|"
    r"COURT|"
    r"COURTS|"
    r"COVE|"
    r"COVES|"
    r"CP|"
    r"CPE|"
    r"CRCL|"
    r"CRCLE|"
    r"CREEK|"
    r"CRES|"
    r"CRESCENT|"
    r"CREST|"
    r"CRK|"
    r"CROSSING|"
    r"CROSSROAD|"
    r"CROSSROADS|"
    r"CRSE|"
    r"CRSENT|"
    r"CRSNT|"
    r"CRSSNG|"
    r"CRST|"
    r"CSWY|"
    r"CT|"
    r"CTR|"
    r"CTRS|"
    r"CTS|"
    r"CURV|"
    r"CURVE|"
    r"CV|"
    r"CVS|"
    r"CYN|"
    r"DALE|"
    r"DAM|"
    r"DIV|"
    r"DIVIDE|"
    r"DL|"
    r"DM|"
    r"DR|"
    r"DRIV|"
    r"DRIVE|"
    r"DRIVES|"
    r"DRS|"
    r"DRV|"
    r"DV|"
    r"DVD|"
    r"EST|"
    r"ESTATE|"
    r"ESTATES|"
    r"ESTS|"
    r"EXP|"
    r"EXPR|"
    r"EXPRESS|"
    r"EXPRESSWAY|"
    r"EXPW|"
    r"EXPY|"
    r"EXT|"
    r"EXTENSION|"
    r"EXTENSIONS|"
    r"EXTN|"
    r"EXTNSN|"
    r"EXTS|"
    r"FALL|"
    r"FALLS|"
    r"FERRY|"
    r"FIELD|"
    r"FIELDS|"
    r"FLAT|"
    r"FLATS|"
    r"FLD|"
    r"FLDS|"
    r"FLS|"
    r"FLT|"
    r"FLTS|"
    r"FORD|"
    r"FORDS|"
    r"FOREST|"
    r"FORESTS|"
    r"FORG|"
    r"FORGE|"
    r"FORGES|"
    r"FORK|"
    r"FORKS|"
    r"FORT|"
    r"FRD|"
    r"FRDS|"
    r"FREEWAY|"
    r"FREEWY|"
    r"FRG|"
    r"FRGS|"
    r"FRK|"
    r"FRKS|"
    r"FRRY|"
    r"FRST|"
    r"FRT|"
    r"FRWAY|"
    r"FRWY|"
    r"FRY|"
    r"FT|"
    r"FWY|"
    r"GARDEN|"
    r"GARDENS|"
    r"GARDN|"
    r"GATEWAY|"
    r"GATEWY|"
    r"GATWAY|"
    r"GDN|"
    r"GDNS|"
    r"GLEN|"
    r"GLENS|"
    r"GLN|"
    r"GLNS|"
    r"GRDEN|"
    r"GRDN|"
    r"GRDNS|"
    r"GREEN|"
    r"GREENS|"
    r"GRN|"
    r"GRNS|"
    r"GROV|"
    r"GROVE|"
    r"GROVES|"
    r"GRV|"
    r"GRVS|"
    r"GTWAY|"
    r"GTWY|"
    r"HARB|"
    r"HARBOR|"
    r"HARBORS|"
    r"HARBR|"
    r"HAVEN|"
    r"HBR|"
    r"HBRS|"
    r"HEIGHTS|"
    r"HIGHWAY|"
    r"HIGHWY|"
    r"HILL|"
    r"HILLS|"
    r"HIWAY|"
    r"HIWY|"
    r"HL|"
    r"HLLW|"
    r"HLS|"
    r"HOLLOW|"
    r"HOLLOWS|"
    r"HOLW|"
    r"HOLWS|"
    r"HRBOR|"
    r"HT|"
    r"HTS|"
    r"HVN|"
    r"HWAY|"
    r"HWY|"
    r"INLET|"
    r"INLT|"
    # r"IS|"
    r"ISLAND|"
    r"ISLANDS|"
    r"ISLE|"
    r"ISLES|"
    r"ISLND|"
    r"ISLNDS|"
    r"ISS|"
    r"JCT|"
    r"JCTION|"
    r"JCTN|"
    r"JCTNS|"
    r"JCTS|"
    r"JUNCTION|"
    r"JUNCTIONS|"
    r"JUNCTN|"
    r"JUNCTON|"
    r"KEY|"
    r"KEYS|"
    r"KNL|"
    r"KNLS|"
    r"KNOL|"
    r"KNOLL|"
    r"KNOLLS|"
    r"KY|"
    r"KYS|"
    r"LAKE|"
    r"LAKES|"
    r"LAND|"
    r"LANDING|"
    r"LANE|"
    r"LCK|"
    r"LCKS|"
    r"LDG|"
    r"LDGE|"
    r"LF|"
    r"LGT|"
    r"LGTS|"
    r"LIGHT|"
    r"LIGHTS|"
    r"LK|"
    r"LKS|"
    r"LN|"
    r"LNDG|"
    r"LNDNG|"
    r"LOAF|"
    r"LOCK|"
    r"LOCKS|"
    r"LODG|"
    r"LODGE|"
    r"LOOP|"
    r"LOOPS|"
    r"MALL|"
    r"MANOR|"
    r"MANORS|"
    r"MDW|"
    r"MDWS|"
    r"MEADOW|"
    r"MEADOWS|"
    r"MEDOWS|"
    r"MEWS|"
    r"MILL|"
    r"MILLS|"
    r"MISSION|"
    r"MISSN|"
    r"ML|"
    r"MLS|"
    r"MNR|"
    r"MNRS|"
    r"MNT|"
    r"MNTAIN|"
    r"MNTN|"
    r"MNTNS|"
    r"MOTORWAY|"
    r"MOUNT|"
    r"MOUNTAIN|"
    r"MOUNTAINS|"
    r"MOUNTIN|"
    r"MSN|"
    r"MSSN|"
    r"MT|"
    r"MTIN|"
    r"MTN|"
    r"MTNS|"
    r"MTWY|"
    r"NCK|"
    # r"NECK|"
    r"OPAS|"
    r"ORCH|"
    r"ORCHARD|"
    r"ORCHRD|"
    r"OVAL|"
    r"OVERPASS|"
    r"OVL|"
    r"PARK|"
    r"PARKS|"
    r"PARKWAY|"
    r"PARKWAYS|"
    r"PARKWY|"
    r"PASS|"
    r"PASSAGE|"
    r"PATH|"
    r"PATHS|"
    r"PIKE|"
    r"PIKES|"
    r"PINE|"
    r"PINES|"
    r"PKWAY|"
    r"PKWY|"
    r"PKWYS|"
    r"PKY|"
    r"PL|"
    r"PLACE|"
    r"PLAIN|"
    r"PLAINS|"
    r"PLAZA|"
    r"PLN|"
    r"PLNS|"
    r"PLZ|"
    r"PLZA|"
    r"PNE|"
    r"PNES|"
    r"POINT|"
    r"POINTS|"
    r"PORT|"
    r"PORTS|"
    r"PR|"
    r"PRAIRIE|"
    r"PRK|"
    r"PRR|"
    r"PRT|"
    r"PRTS|"
    r"PSGE|"
    r"PT|"
    r"PTS|"
    r"RAD|"
    r"RADIAL|"
    r"RADIEL|"
    r"RADL|"
    r"RAMP|"
    r"RANCH|"
    r"RANCHES|"
    r"RAPID|"
    r"RAPIDS|"
    r"RD|"
    r"RDG|"
    r"RDGE|"
    r"RDGS|"
    r"RDS|"
    r"REST|"
    r"RIDGE|"
    r"RIDGES|"
    r"RIV|"
    r"RIVER|"
    r"RIVR|"
    r"RNCH|"
    r"RNCHS|"
    r"ROAD|"
    r"ROADS|"
    r"(?:ROUTE|RTE|RT)\s+\d+|"
    r"ROW|"
    r"RPD|"
    r"RPDS|"
    r"RST|"
    r"RUE|"
    r"RUN|"
    r"RVR|"
    r"SHL|"
    r"SHLS|"
    r"SHOAL|"
    r"SHOALS|"
    r"SHOAR|"
    r"SHOARS|"
    r"SHORE|"
    r"SHORES|"
    r"SHR|"
    r"SHRS|"
    r"SKWY|"
    r"SKYWAY|"
    r"SMT|"
    r"SPG|"
    r"SPGS|"
    r"SPNG|"
    r"SPNGS|"
    r"SPRING|"
    r"SPRINGS|"
    r"SPRNG|"
    r"SPRNGS|"
    r"SPUR|"
    r"SPURS|"
    r"SQ|"
    r"SQR|"
    r"SQRE|"
    r"SQRS|"
    r"SQS|"
    r"SQU|"
    r"SQUARE|"
    r"SQUARES|"
    r"ST|"
    r"STA|"
    r"STATION|"
    r"STATN|"
    r"STN|"
    r"STR|"
    r"STRA|"
    r"STRAV|"
    r"STRAVEN|"
    r"STRAVENUE|"
    r"STRAVN|"
    r"STREAM|"
    r"STREET|"
    r"STREETS|"
    r"STREME|"
    r"STRM|"
    r"STRT|"
    r"STRVN|"
    r"STRVNUE|"
    r"STS|"
    r"SUMIT|"
    r"SUMITT|"
    r"SUMMIT|"
    r"TER|"
    r"TERR|"
    r"TERRACE|"
    r"THROUGHWAY|"
    r"TPKE|"
    r"TRACE|"
    r"TRACES|"
    r"TRACK|"
    r"TRACKS|"
    r"TRAFFICWAY|"
    r"TRAIL|"
    r"TRAILER|"
    r"TRAILS|"
    r"TRAK|"
    r"TRCE|"
    r"TRFY|"
    r"TRK|"
    r"TRKS|"
    r"TRL|"
    r"TRLR|"
    r"TRLRS|"
    r"TRLS|"
    r"TRNPK|"
    r"TRWY|"
    r"TUNEL|"
    r"TUNL|"
    r"TUNLS|"
    r"TUNNEL|"
    r"TUNNELS|"
    r"TUNNL|"
    r"TURNPIKE|"
    r"TURNPK|"
    r"UN|"
    r"UNDERPASS|"
    r"UNION|"
    r"UNIONS|"
    r"UNS|"
    r"UPAS|"
    r"VALLEY|"
    r"VALLEYS|"
    r"VALLY|"
    r"VDCT|"
    r"VIA|"
    r"VIADCT|"
    r"VIADUCT|"
    r"VIEW|"
    r"VIEWS|"
    r"VILL|"
    r"VILLAG|"
    r"VILLAGE|"
    r"VILLAGES|"
    r"VILLE|"
    r"VILLG|"
    r"VILLIAGE|"
    r"VIS|"
    r"VIST|"
    r"VISTA|"
    r"VL|"
    r"VLG|"
    r"VLGS|"
    r"VLLY|"
    r"VLY|"
    r"VLYS|"
    r"VST|"
    r"VSTA|"
    r"VW|"
    r"VWS|"
    r"WALK|"
    r"WALKS|"
    r"WALL|"
    r"WAY|"
    r"WAYS|"
    r"WELL|"
    r"WELLS|"
    r"WL|"
    r"WLS|"
    r"WY|"
    r"XING|"
    r"XRD|"
    r"XRDS"
    r")\.?)"
)
SECONDARY_ADDRESS: str = (
    r"(?:"
    r"#|"
    r"APT\.?|"
    r"BSMT|"
    r"BLDG|"
    r"DEPT|"
    r"FL|"
    r"FRNT|"
    r"HNGR|"
    r"KEY|"
    r"LBBY|"
    r"LOT|"
    r"LOWR|"
    r"OFC|"
    r"PH|"
    r"PIER|"
    r"REAR|"
    r"RM|"
    r"SIDE|"
    r"SLIP|"
    r"SPC|"
    r"STOP|"
    r"STE|"
    r"TRLR|"
    r"UNIT|"
    r"UPPR"
    r")"
    r"\s*"
    r"(?:(?:(?:#\s*)?\d+)|[a-z]+)"
)

DELIVERY_ADDRESS_LINE: str = (
    r"\d+(?:-\d+)?(?:\s+"
    + DIRECTIONAL
    + r")?(?:\s+[a-z]{3,}){1,4}(?:\s+\d+)?\s+"
    + SUFFIX
    + r"(?: "
    + DIRECTIONAL
    + r")?(?:\s+"
    + SECONDARY_ADDRESS
    + r")?"
)

CITY_NAME: str = r"(?:[a-z]{2,}(?:\s+|-)){0,4}[a-z]{3,}"
STATE_AND_POSSESSIONS: str = (
    r"(?:"
    r"AL|Alabama"
    r"|AK|Alaska"
    r"|AZ|Arizona"
    r"|AR|Arkansas"
    r"|CA|California"
    r"|CO|Colorado"
    r"|CT|Connecticut"
    r"|DE|Delaware"
    r"|FL|Florida"
    r"|GA|Georgia"
    r"|HI|Hawaii"
    r"|ID|Idaho"
    r"|IL|Illinois"
    r"|IN|Indiana"
    r"|IA|Iowa"
    r"|KS|Kansas"
    r"|KY|Kentucky"
    r"|LA|Louisiana"
    r"|ME|Maine"
    r"|MD|Maryland"
    r"|MA|Massachusetts"
    r"|MI|Michigan"
    r"|MN|Minnesota"
    r"|MS|Mississippi"
    r"|MO|Missouri"
    r"|MT|Montana"
    r"|NE|Nebraska"
    r"|NV|Nevada"
    r"|NH|New Hampshire"
    r"|NJ|New Jersey"
    r"|NM|New Mexico"
    r"|NY|New York"
    r"|NC|North Carolina"
    r"|ND|North Dakota"
    r"|OH|Ohio"
    r"|OK|Oklahoma"
    r"|OR|Oregon"
    r"|PA|Pennsylvania"
    r"|RI|Rhode Island"
    r"|SC|South Carolina"
    r"|SD|South Dakota"
    r"|TN|Tennessee"
    r"|TX|Texas"
    r"|UT|Utah"
    r"|VT|Vermont"
    r"|VA|Virginia[H]"
    r"|WA|Washington"
    r"|WV|West Virginia"
    r"|WI|Wisconsin"
    r"|WY|Wyoming"
    r")"
)

ZIP_CODE = r"(?:\d{5}(?:-?\d{4})?)"

COUNTRY = r"(?:USA|U.S.A.|U.S.|United\s+States\s+of\s+America)"


class USPostalAddress(Identifier):
    def __init__(self) -> None:
        options = re2.Options()
        options.case_sensitive = False
        self.patterns: list[Pattern[str]] = [
            re2.compile(
                r"^(?:"
                + r"(?:"
                + DELIVERY_ADDRESS_LINE
                + r"(?:"
                + SEPARATOR
                + CITY_NAME
                + SEPARATOR
                + STATE_AND_POSSESSIONS
                + r"(?:"
                + SEPARATOR
                + ZIP_CODE
                + r"(?:"
                + SEPARATOR
                + COUNTRY
                + r")?)?)?)"
                r"|(?:(?:(?:(?:"
                + SECONDARY_ADDRESS
                + SEPARATOR
                + r")?"
                + DELIVERY_ADDRESS_LINE
                + SEPARATOR
                + r")?"
                + CITY_NAME
                + SEPARATOR
                + r")?"
                + STATE_AND_POSSESSIONS
                + SEPARATOR
                + ZIP_CODE
                + r")"
                r"|(?:\d+(?:-\d+)?(?:\s+"
                + DIRECTIONAL
                + r")?(?:\s+[a-zA-Z]{3,}){1,4}(?:\s+\d+)?\s+"
                + SUFFIX
                + r"(?: "
                + DIRECTIONAL
                + r")?(?:\s+"
                + SECONDARY_ADDRESS
                + r")?(?:"
                + SEPARATOR
                + r"(?:\s+[a-zA-Z]{3,}){1,4})?)"
                r"|(?:\d+(?:\s+\w{3,})+(?:\s+\d+)?,?(?:\s+\w{3,})+,?(?:\s+\w{3,})+,?\s+"
                + COUNTRY
                + r"\s+\d{4,5}(?:-\d{4,5})?)"
                r"|(?:\d+\s+" + DIRECTIONAL + r"(?:\s+\w{3,})+\s+\d+,?\s+\d{3,})" + r")$",
                options,
            ),
            re2.compile(
                r"^(?:"
                + r"(?:\d+(?:\s+\w{3,})+\s+"
                + SUFFIX
                + r",?(?:\s+\w{3,})+,?(?:\s+\w{3,})+,?\s+"
                + STATE_AND_POSSESSIONS
                + r")"
                r"|(?:\w{3,}(:?\s+\w{3,})*,?\s+" + STATE_AND_POSSESSIONS + r",?\s+" + ZIP_CODE + r"(?:\s+\w{2,})+)"
                r"|(?:\d+(?:\s+\w{3,})*(?:\s+"
                + SUFFIX
                + r")?,?\s+"
                + CITY_NAME
                + r",?\s+"
                + STATE_AND_POSSESSIONS
                + r",?\s+"
                + ZIP_CODE
                + r"(?:\s+\w{2,})+)"
                r"|(?:\d+\s+"
                + DIRECTIONAL
                + r"(?:\s+\w{2,})+\s+"
                + SUFFIX
                + SEPARATOR
                + r"(?:\s+\w{3,})+"
                + SEPARATOR
                + r"(?:\s+\w{3,})+"
                + SEPARATOR
                + r"\s+"
                + STATE_AND_POSSESSIONS
                + r")"
                r"|(?:\d+\s+"
                + SUFFIX
                + r"(?:\s+\w{1,})+"
                + SEPARATOR
                + r"(?:\s+\w{3,})+"
                + SEPARATOR
                + r"(?:\s+\w{3,})+"
                + SEPARATOR
                + r"\s+"
                + STATE_AND_POSSESSIONS
                + r")"
                + r")$",
                options,
            ),
        ]

    def is_of_this_type(self, text: str) -> bool:
        if len(text) < 5 or len(text) >= 128 or not _quick_check_there_are_multiple_tokens(text):
            return False

        if not _check_that_case_is_consistent(text):
            return False

        return any(pattern.match(text) for pattern in self.patterns)


def _quick_check_there_are_multiple_tokens(text: str) -> bool:
    return len(text.split()) >= 3


def _check_that_case_is_consistent(text: str) -> bool:
    """Check if the text has consistent casing (all uppercase or all lowercase initial letters).

    Args:
        text: The text to check for case consistency

    Returns:
        bool: True if all alphabetic initial letters are consistently upper or lower case,
              False if mixed case is detected
    """
    import re

    # Split on whitespace and commas using proper regex
    tokens = re.split(r"[\s,]+", text)

    upper_count = 0
    lower_count = 0

    for token in tokens:
        token = token.strip()
        if not token:
            continue

        # Get first character
        first_char = token[0]

        if first_char.isalpha():
            if first_char.islower():
                lower_count += 1
            elif first_char.isupper():
                upper_count += 1
            # Note: Non-ASCII alphabetic characters that are neither upper nor lower
            # are ignored rather than causing the function to return False

    # Return True if case is consistent: either all upper OR all lower (not both)
    # If no alphabetic characters found, consider it consistent (return True)
    has_mixed_case = lower_count > 0 and upper_count > 0
    return not has_mixed_case
