import pytest
from faker import Faker

from risk_assessment.classification.identifiers import SWIFT


@pytest.mark.skip(reason="SWIFT codes generated by Faker seem not corresponding to the standard")
def test_positive(faker: Faker) -> None:
    identifier = SWIFT()

    missed: set[str] = set()
    count: int = 0

    for _ in range(10_000):
        swift = faker.swift()

        if swift in missed:
            continue

        if not identifier.is_of_this_type(swift):
            missed.add(swift)

        count += 1

    assert len(missed) / count < 0.01, missed  # assuming our dictionary is smaller than what Faker can generate


def test_from_rwd():
    identifier = SWIFT()

    for valid in [
        "NRTHUS33XXX",
        "TDOMCATTTOR",
    ]:
        assert identifier.is_of_this_type(valid), valid
